version: '3'

services:
  achieve_edge:
    image: docker.pkg.github.com/it108/achieve-edge/achieve-edge:${GITHUB_SHA}
    container_name: achieve_edge
    environment:
        EDGE_API_TOKEN: ${API_TOKEN}
        API_ADDRESS: ${API_ADDRESS}
        DB_CONN_STRING: ${DB_CONN_STRING}
    ports:
      - "${EDGE_PORT_PROD}:80"
    restart: always
    networks:
      - achieve_edge_prod

networks:
  achieve_edge_prod:
