version: '3'

services:
  achieve_api:
    image: docker.pkg.github.com/${GITHUB_REPOSITORY}/achieve-api:${GITHUB_SHA}
    container_name: achieve_api
    environment:
        EDGE_API_TOKEN: ${API_TOKEN}
        EDGE_ADDRESS: ${EDGE_ADDRESS}
        DB_CONN_STRING: ${DB_CONN_STRING}
    ports:
      - "${API_PORT_PROD}:80"
    restart: always
    networks:
      - achieve_api_prod

networks:
  achieve_api_prod:
